### ISSUE TITLE
Unable to revoke and remove service account keys

### ISSUE THREAD

**Issue by steven-twingate** [Twingate-Labs/tg-cli#10]
Currently it is possible to create service account keys but not possible to revoke and remove. It would be nice to have this ability in order to programmatically rotate service account keys.

**Comment by chenbishop** [comment]
Hi @steven-twingate that makes sense, we will look into this and keep you updated.

**Comment by chenbishop** [comment]
@steven-twingate, we just released [0.0.69](https://github.com/Twingate-Labs/tg-cli/releases/tag/v0.0.69) and it includes this feature.

To revoke a service key, use the following command

`./tg service key_revoke <serviceAccountKeyId>`
