### ISSUE TITLE
`resource create` command doesn't recognize group name

### ISSUE THREAD

**Issue by alexmensch** [Twingate-Labs/tg-cli#5]
I'm running the suggested command after using `deploy do` and am receiving the following error:

```
➜  ~ ./tg resource create "Digital Ocean (sfo3)" "Connector host tg-primitive-mayfly" "10.124.0.3" Everyone
[INFO]    Using Twingate account: 'tenant'
[ERROR]   Exception: Error: Could not find group: 'E'
    at Command.fn (file:///home/runner/work/tg-cli/tg-cli/tg.bundle.js:10357:39)
    at async Command.execute (file:///home/runner/work/tg-cli/tg-cli/tg.bundle.js:2470:13)
    at async main2 (file:///home/runner/work/tg-cli/tg-cli/tg.bundle.js:80076:12)
    at async file:///home/runner/work/tg-cli/tg-cli/tg.bundle.js:80079:5
```

I also tried enclosing `"Everyone"` in quotes, and the CLI returns with the same error message.

**Comment by emrul** [comment]
Hi @alexmensch thank you for reporting this. We have found that an update to our CLI framework appears to have broken handling of variadic arguments (report [here](https://github.com/c4spar/deno-cliffy/issues/455)).

In the meantime we have reverted to the prior version of the framework and verified it corrects the problem. Can you retry and let me know if you face any further issues?

**Comment by alexmensch** [comment]
Works, thanks!
