### ISSUE TITLE
The readme instructions for Linux have incorrect command, it's `tgcli` vs `tg`

### ISSUE THREAD

**Issue by robotparty** [Twingate-Labs/tg-cli#8]
That's it really... `tgcli --help` works (I installed the .deb package if that matters)

**Comment by emrul** [comment]
Hi @robotparty - thanks for reporting this. It's due to an oversight on our part. It should be called `tg` so we're going to update the package to correct this.

**Comment by chenbishop** [comment]
Thank you for raising the issue, this is fixed from version v0.0.67.
